# Generated by Django 5.2.1 on 2025-06-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
