# Generated by Django 5.2.1 on 2025-06-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_metric_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='groups',
        ),
    ]
