# Generated by Django 5.2.1 on 2025-06-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_metric_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='review_cycles',
            field=models.ManyToManyField(blank=True, to='review.reviewcycle'),
        ),
    ]
