# Generated by Django 5.2.1 on 2025-06-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_metric_review_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='review_cycles',
            field=models.ManyToManyField(blank=True, related_name='metrics', to='review.reviewcycle'),
        ),
    ]
